### ISSUE TITLE
Support for Last Will + Connected state

### ISSUE THREAD

**Issue by i8beef** [Edubits/Zway-MQTT#33] opened 2018-08-18 05:53 UTC
Any interest in allowing for last will + connect notification? Something like adopting the "Connected status" of this semi-standard? https://github.com/mqtt-smarthome/mqtt-smarthome/blob/master/Architecture.md

With the current approach to topics, you actually could just automatically set up the last will topic at `topicPrefix/connected` with payload `0` and `retain`, and then just publish to the same topic but with `1` on successful connect.

This could actually have an added benefit of allowing some of us to monitor connections a bit more actively.

**Comment by Edubits** [comment] 2018-08-19 20:54
Sounds like a good addition! Also good to see someone developed a standard which is very similar to how we set up our home automation as well, I didn't know it yet.

As your PR also involved some connection logic changes I looked into this as well and also found that it (at least on my Raspberry Pi setup) sometimes takes slightly longer than 10s for the connection to be fully done, which caused the connection timeout to kick in, which in turns closes the connection and keeps repeated until it succeeds. So it probably makes sense to increase it to e.g. 30s. What do you think about this?

Merging and releasing a new version will take a bit longer as I'm leaving for holiday soon.

**Comment by i8beef** [comment] 2018-08-19 21:19
I actually like your approach of suffixing the MQTT message with `/set`, etc. instead of their approach... but other than that, yeah its a good start. They aren't very responsive to suggestions though...  :-/

But I did like their idea for the connected state, so I stole it. Notice my other issue would allow someone to conform to their MQTT message format if they wanted to, but let those of us who like your approach better to continue with that.

I don't think the changes I made around connection stuff should cause that... I added a lock check for if the module has been stopped manually so it properly lets the connection die in that case, and I fixed a reconnect check that was SUPPOSED to bail if a connection was already established (a just in case check, that probably isn't ever hit) to protect from the possibility of a runaway reconnect accidentally kicking an established client.

A last will shouldn't really cause that either that I'm aware of... at least on Mosquitto I haven't seen that, though I guess anything is possible with different brokers?

**Comment by Edubits** [comment] 2018-08-20 08:04
> I don't think the changes I made around connection stuff should cause that

I agree, I wasn't clear enough: your changes made me look into this, they were not the cause!

**Comment by i8beef** [comment] 2018-08-20 18:08
Phew, scared me there for a second.

**Comment by i8beef** [comment] 2018-08-21 22:08
Updated due to a bug I had in there around that isConnected flag not getting reset.

**Comment by bjw-s** [comment] 2018-10-30 06:47
@Edubits Do you happen to see any chance to merge this PR in the coming time? (assuming that you are back from your holiday) 👼

**Comment by Edubits** [comment] 2018-10-31 20:30
Thanks for the reminder @Juggels, I merged it yesterday. I also did some additional changes, see #36.

**Closed as completed by Edubits** 2018-10-31 20:30 UTC
