### ISSUE TITLE
mqtt reconnection logic still broken

### ISSUE THREAD

**Issue by TobbeJ** [Edubits/Zway-MQTT#16] opened 2017-01-01 22:57 UTC
Hello

i updated this plugin to the new v1.1 version and the reconnection logic appears to still be broken.
my zway server is behind a sometimes unstable 4g connection and mqtt server on other side of the link, so connection tends to go down from time to time and this plugin cant recover properly.

it looks like it is trying to reconnect a few times but then eventually gives up.

i don't know how it is done in this plugin but it needs to keep retrying the connection indefinitely possibly with a user configurable delay between tries.
right now it is not reliable which means i can unfortunately not use this plugin and need to come up with another solution

**Comment by Edubits** [comment] 2017-01-07 09:55
Sorry to hear that @TobbeJ! It should keep on trying. Do you have any logging in your z-way-server.log related to the MQTT module?

**Comment by TobbeJ** [comment] 2017-01-07 11:08
yes and lots of it.
please try to minimize logging if possible, zway server already is logging quite a lot already and so far during the year or so ive had it i have managed to get 2 sd cards corrupted most likely due to the high number of writes in the log (i'm on to my 3rd card now...)

anyway, logs

> [2017-01-07 06:25:17.067] [I] [core] true
[2017-01-07 06:25:17.067] [I] [core] true
[2017-01-07 06:25:17.068] [I] [core] true
[2017-01-07 06:25:17.089] [I] [core] true
[2017-01-07 06:25:17.089] [I] [core] true
[2017-01-07 06:25:17.089] [I] [core] true
[2017-01-07 06:25:17.090] [I] [core] true
[2017-01-07 06:25:17.090] [I] [core] true
[2017-01-07 06:25:17.090] [I] [core] true
[2017-01-07 06:25:17.091] [I] [core] true
[2017-01-07 06:25:17.091] [I] [core] true
[2017-01-07 06:25:17.237] [I] [core] [MQTT_11] Error: Error: Please connect to server first
    at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
    at null._errorCallback (automation/userModules/MQTT/index.js:105:8)
    at MQTTClient._onError (automation/userModules/MQTT/lib/mqtt.js:449:10)
    at MQTTClient.ping (automation/userModules/MQTT/lib/mqtt.js:564:10)
    at Function.<anonymous> (automation/userModules/MQTT/lib/mqtt.js:164:14)
[2017-01-07 06:25:17.295] [I] [core] [MQTT_11] Error: Error: Please connect to server first
    at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
    at null._errorCallback (automation/userModules/MQTT/index.js:105:8)
    at MQTTClient._onError (automation/userModules/MQTT/lib/mqtt.js:449:10)
    at MQTTClient.ping (automation/userModules/MQTT/lib/mqtt.js:564:10)
    at Function.<anonymous> (automation/userModules/MQTT/lib/mqtt.js:164:14)
[2017-01-07 06:25:17.335] [I] [core] [MQTT_11] Error: Disconnected, will retry to connect...
    at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
    at null._disconnectCallback (automation/userModules/MQTT/index.js:109:8)
    at MQTTClient._onClose (automation/userModules/MQTT/lib/mqtt.js:459:10)
    at tcp.connection.onclose (automation/userModules/MQTT/lib/mqtt.js:332:10)
[2017-01-07 06:25:17.542] [I] [core] true
[2017-01-07 06:25:17.548] [I] [core] true
[2017-01-07 06:25:17.548] [I] [core] true
[2017-01-07 06:25:17.548] [I] [core] true
[2017-01-07 06:25:17.549] [I] [core] true
[2017-01-07 06:25:17.549] [I] [core] true
[2017-01-07 06:25:17.550] [I] [core] true
[2017-01-07 06:25:17.550] [I] [core] true

and stuff like:

> [2017-01-07 06:25:16.840] [I] [core] true
[2017-01-07 06:25:16.840] [I] [core] true
[2017-01-07 06:25:16.841] [I] [core] true
[2017-01-07 06:25:16.841] [I] [core] true
[2017-01-07 06:25:16.894] [E] [core] Callback execution error: TypeError: Cannot read property 'write' of undefined
    at MQTTClient.subscribe (automation/userModules/MQTT/lib/mqtt.js:555:18)
    at null._connectionCallback (automation/userModules/MQTT/index.js:67:15)
    at MQTTClient._onConnect (automation/userModules/MQTT/lib/mqtt.js:454:10)
    at MQTTClient.messageHandlers.(anonymous function) (automation/userModules/MQTT/lib/mqtt.js:166:12)
    at MQTTClient._onData (automation/userModules/MQTT/lib/mqtt.js:477:9)
    at tcp.connection.onrecv (automation/userModules/MQTT/lib/mqtt.js:328:10)
[2017-01-07 06:25:16.918] [I] [core] [MQTT_11] Error: Disconnected, will retry to connect...
    at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
    at null._disconnectCallback (automation/userModules/MQTT/index.js:109:8)
    at MQTTClient._onClose (automation/userModules/MQTT/lib/mqtt.js:459:10)
    at tcp.connection.onclose (automation/userModules/MQTT/lib/mqtt.js:332:10)
[2017-01-07 06:25:17.057] [I] [core] true
[2017-01-07 06:25:17.057] [I] [core] true
[2017-01-07 06:25:17.057] [I] [core] true

**Comment by Edubits** [comment] 2017-01-07 11:26
Thanks for sharing. That seems to be a very similar issue as #17.
Considering logging: I always falsely assumed the `[core] true` log was from the core of Z-Way, but it seems it's caused by a wrongly implemented method inside the buffer.js library. Could you try to replace the implementation of `assert.ok` with the following to see if this removes the unnecessary logging?
```javascript
var assert = {};
assert.ok = function (condition, message) {
	if (!condition) {
		console.log(message);
	}
};
```

**Comment by TobbeJ** [comment] 2017-01-08 08:10
first of all, the current implementation of assert.ok is missing a parameter compared to how it is called.
this is what i have:

> var assert = {};
assert.ok = function (message) {
<------>console.log(message);
};

and all over the place it is used with two parameters.

**Comment by TobbeJ** [comment] 2017-01-08 08:21
i've made the changes and it looks promising.

yesterday i made some other changes and installed a local mqtt server and pointed this pluggin to it instead of the remote mqtt server and then setup an mqtt bridge between the two mqtt servers.
but even when this plugin only talks to a local mqtt server on the same host it still gives up for some reason.
log was full of stuff that indicated it had run out of filehandles and it also looks like it was reconnecting realy quick (or trying to).
/var/log/z-way-server was around 640mb in size

it looks as if it is trying to reconnect to the local mqtt server over and over even when it never went down

**Comment by Edubits** [comment] 2017-01-08 10:29
> first of all, the current implementation of assert.ok is missing a parameter compared to how it is called

Indeed, I fixed that in the version from my comment. If this gets rid of all the `[core] true` comments (which I suppose) I will refactor it a bit more, so it will include (in case of an error) the MQTT prefix, so it's clear from which module the message comes.

We should definitely add some rate limiting and make sure it can only try once at a time. I'll look into that! It would still be interesting to see which errors (especially the first few) it runs into, on my local install it's pretty stable: never had these reconnect loops.

**Comment by TobbeJ** [comment] 2017-01-08 10:35
no "[core] true" messages any more

perhaps you can simulate connection problems by just restarting mqtt server or temporarily unplug network between zway server and mqtt server.

**Comment by Edubits** [comment] 2017-01-08 16:04
I've just pushed some changes to the 1.2 branch, could you guys give that version a try?
(cc: @mrnmukkas, @i8beef, @TobbeJ)

**Comment by i8beef** [comment] 2017-01-09 23:03
Downloaded and am running it. Will watch it to see if I have any issues over the next few days. Haven't tried cycling the MQTT server yet.

**Comment by Edubits** [comment] 2017-01-10 08:56
Thanks @i8beef, looking forward to your results.

**Comment by mrnmukkas** [comment] 2017-01-10 20:00
I'm only getting a few (three timeouts in ~14 hours) of these now:

> [2017-01-10 15:50:00.394] [I] [core] [MQTT_45] Error: Error: Timeout
    at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
    at null._errorCallback (automation/userModules/MQTT/index.js:114:8)
    at MQTTClient._onError (automation/userModules/MQTT/lib/mqtt.js:411:10)
    at MQTTClient._onTimeout (automation/userModules/MQTT/lib/mqtt.js:405:8)
    at Function.<anonymous> (automation/userModules/MQTT/lib/mqtt.js:539:12)
[...]
[2017-01-10 15:50:00.444] [I] [core] [MQTT_45] Error: Disconnected, will retry to connect...
    at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
    at null._disconnectCallback (automation/userModules/MQTT/index.js:123:9)
    at MQTTClient._onClose (automation/userModules/MQTT/lib/mqtt.js:424:9)
    at tcp._connection.onclose (automation/userModules/MQTT/lib/mqtt.js:294:10)
[...]
[2017-01-10 15:50:01.826] [I] [core] [MQTT-45] Trying to reconnect (1)
[...]
[2017-01-10 15:50:02.969] [I] [core] [MQTT-45] Connected to localhost

**Comment by mrnmukkas** [comment] 2017-01-17 20:05
I'd like to add that the 1.2 update seems to have also solved a crash I was experiencing with the zway server (http://forum.z-wave.me/viewtopic.php?f=3419&t=23948#p66242) where too many connection were being opened without closing which made the server shut down after running for about ten hours. Since the update my server has been rock solid and MQTT via Node Red is working like a charm! There are no MQTT errors present in the zway log either.

**Comment by Edubits** [comment] 2017-01-19 09:34
That's great news @mrnmukkas! @i8beef how is the version behaving on your side?

**Comment by i8beef** [comment] 2017-01-24 03:01
I mean, its still been running ok for me. I've had a power failure or two since its been running, but that blinks both Pi's at once, so I'm not sure that's a good test of the reconnection stuff... I'm tempted to just turn the MQTT server off for a few hours to see what effect it has on the module.

**Comment by Edubits** [comment] 2017-01-24 13:04
Thanks @i8beef for testing.

I've just submitted version 1.2 to the app store. If you added the `mqtt_beta` token you can already install it.

**Closed as completed by Edubits** 2017-01-24 13:04 UTC
